### PR TITLE
Sonoff mini update

### PR DESCRIPTION
**Pull request by FixxCZ**
Just add mini as it's working all right.

### CODE REVIEW

**Comment by peterbuga** [comment]
thanks!

**Comment by Postixer** [comment]
Io non riesco a farlo funzionare, seguendo la guida per filo e per segno non mi esce l'interruttore per accendere/spegnere

**Comment by peterbuga** [comment]
@Postixer chiedi a qualcuno que parla / legge inglese per aiutare
## respect the community => **write in english**!

**Comment by Postixer** [comment]
I beg your pardon, I would also like to install this custom component, I state that I have installed on the docker and the custom_components folder I had to create myself in / config, I copied the sonoff folder with the 3 files and compiled the yaml configuration file but nothing is activated

**Pull request merged**
