### PR TITLE
Add version 3.0.0 and verify Sonoff RF, S26, Basic and 1 Gang Wall Switch

### PR DESCRIPTION
**Pull request by GuyKh**

### CODE REVIEW

**Comment by GuyKh** [comment]
@Tony763 done - added as verified

**Comment by 2016for** [comment]
Can confirm: Sonoff Basic version 3.0.0

**Comment by GuyKh** [comment]
> Can confirm: Sonoff Basic version 3.0.0
> 
> You can add this too

Added. Thanks! :)

**Comment by peterbuga** [comment]
thanks!

**Pull request merged**
